# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name=b'URL')),
                ('image', models.ImageField(upload_to=b'publicidad/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=b'avatar/')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('resume', models.TextField(verbose_name='Resumen')),
                ('cover', models.ImageField(blank=True, upload_to=b'cover/', verbose_name='Portada')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('cover', models.ImageField(blank=True, upload_to=b'portfolio/', verbose_name='Imagen')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Author')),
            ],
        ),
        migrations.CreateModel(
            name='LinkAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('url', models.CharField(max_length=500, verbose_name=b'URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Author')),
            ],
        ),
        migrations.CreateModel(
            name='LinkObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('url', models.CharField(max_length=500, verbose_name=b'URL')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('resume', models.TextField(verbose_name='Resumen')),
                ('status', models.CharField(choices=[(b'Finalizada', 'Obra Finalizada'), (b'Continuada', 'Obra Continuada'), (b'Unico', 'Cap\xedtulo \xdanico')], default=b'Continuada', max_length=20, verbose_name='Status')),
                ('cover', models.ImageField(blank=True, upload_to=b'cover/', verbose_name='Portada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Author', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('body', models.TextField()),
                ('spotlight', models.BooleanField(default=False, verbose_name='Destacado')),
                ('spotlight_image', models.ImageField(blank=True, upload_to=b'spotlight/', verbose_name='Imagen para Destacar')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Author', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PtoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('address', models.CharField(max_length=500, verbose_name='Direcci\xf3n')),
                ('ciudad', models.CharField(max_length=500, verbose_name='Ciudad')),
                ('image', models.ImageField(upload_to=b'ptoVenta/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name=b'URL')),
                ('image', models.ImageField(upload_to=b'publicidad/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=500, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=500, verbose_name='Twitter')),
                ('tumblr', models.CharField(blank=True, max_length=500, verbose_name='Tumblr')),
                ('deviantart', models.CharField(blank=True, max_length=500, verbose_name='DeviantArt')),
                ('subcultura', models.CharField(blank=True, max_length=500, verbose_name='Subcultura')),
                ('facebookPageNumber', models.CharField(blank=True, max_length=500, verbose_name='Facebook Page Number')),
            ],
        ),
        migrations.CreateModel(
            name='TagObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='tags',
            field=models.ManyToManyField(null=True, to='front.TagObra'),
        ),
        migrations.AddField(
            model_name='linkobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Obra'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Obra'),
        ),
    ]
